// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/seal-io/walrus/pkg/apis/walrus/v1"
	walrusv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrus/v1"
	scheme "github.com/seal-io/walrus/pkg/clients/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubjectsGetter has a method to return a SubjectInterface.
// A group's client should implement this interface.
type SubjectsGetter interface {
	Subjects(namespace string) SubjectInterface
}

// SubjectInterface has methods to work with Subject resources.
type SubjectInterface interface {
	Create(ctx context.Context, subject *v1.Subject, opts metav1.CreateOptions) (*v1.Subject, error)
	Update(ctx context.Context, subject *v1.Subject, opts metav1.UpdateOptions) (*v1.Subject, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Subject, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SubjectList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Subject, err error)
	Apply(ctx context.Context, subject *walrusv1.SubjectApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Subject, err error)
	Login(ctx context.Context, subjectName string, subjectLogin *v1.SubjectLogin, opts metav1.CreateOptions) (*v1.SubjectLogin, error)
	CreateToken(ctx context.Context, subjectName string, subjectToken *v1.SubjectToken, opts metav1.CreateOptions) (*v1.SubjectToken, error)

	SubjectExpansion
}

// subjects implements SubjectInterface
type subjects struct {
	client rest.Interface
	ns     string
}

// newSubjects returns a Subjects
func newSubjects(c *WalrusV1Client, namespace string) *subjects {
	return &subjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subject, and returns the corresponding subject object, and an error if there is any.
func (c *subjects) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Subject, err error) {
	result = &v1.Subject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Subjects that match those selectors.
func (c *subjects) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SubjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SubjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subjects.
func (c *subjects) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subject and creates it.  Returns the server's representation of the subject, and an error, if there is any.
func (c *subjects) Create(ctx context.Context, subject *v1.Subject, opts metav1.CreateOptions) (result *v1.Subject, err error) {
	result = &v1.Subject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subject).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subject and updates it. Returns the server's representation of the subject, and an error, if there is any.
func (c *subjects) Update(ctx context.Context, subject *v1.Subject, opts metav1.UpdateOptions) (result *v1.Subject, err error) {
	result = &v1.Subject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subjects").
		Name(subject.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subject).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subject and deletes it. Returns an error if one occurs.
func (c *subjects) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subjects").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subjects) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subjects").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subject.
func (c *subjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Subject, err error) {
	result = &v1.Subject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subjects").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied subject.
func (c *subjects) Apply(ctx context.Context, subject *walrusv1.SubjectApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Subject, err error) {
	if subject == nil {
		return nil, fmt.Errorf("subject provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(subject)
	if err != nil {
		return nil, err
	}
	name := subject.Name
	if name == nil {
		return nil, fmt.Errorf("subject.Name must be provided to Apply")
	}
	result = &v1.Subject{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("subjects").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Login takes the representation of a subjectLogin and creates it.  Returns the server's representation of the subjectLogin, and an error, if there is any.
func (c *subjects) Login(ctx context.Context, subjectName string, subjectLogin *v1.SubjectLogin, opts metav1.CreateOptions) (result *v1.SubjectLogin, err error) {
	result = &v1.SubjectLogin{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subjects").
		Name(subjectName).
		SubResource("login").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subjectLogin).
		Do(ctx).
		Into(result)
	return
}

// CreateToken takes the representation of a subjectToken and creates it.  Returns the server's representation of the subjectToken, and an error, if there is any.
func (c *subjects) CreateToken(ctx context.Context, subjectName string, subjectToken *v1.SubjectToken, opts metav1.CreateOptions) (result *v1.SubjectToken, err error) {
	result = &v1.SubjectToken{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subjects").
		Name(subjectName).
		SubResource("token").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subjectToken).
		Do(ctx).
		Into(result)
	return
}
