// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/seal-io/walrus/pkg/apis/walrus/v1"
	walrusv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrus/v1"
	scheme "github.com/seal-io/walrus/pkg/clients/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubjectProvidersGetter has a method to return a SubjectProviderInterface.
// A group's client should implement this interface.
type SubjectProvidersGetter interface {
	SubjectProviders(namespace string) SubjectProviderInterface
}

// SubjectProviderInterface has methods to work with SubjectProvider resources.
type SubjectProviderInterface interface {
	Create(ctx context.Context, subjectProvider *v1.SubjectProvider, opts metav1.CreateOptions) (*v1.SubjectProvider, error)
	Update(ctx context.Context, subjectProvider *v1.SubjectProvider, opts metav1.UpdateOptions) (*v1.SubjectProvider, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SubjectProvider, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SubjectProviderList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SubjectProvider, err error)
	Apply(ctx context.Context, subjectProvider *walrusv1.SubjectProviderApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SubjectProvider, err error)
	SubjectProviderExpansion
}

// subjectProviders implements SubjectProviderInterface
type subjectProviders struct {
	client rest.Interface
	ns     string
}

// newSubjectProviders returns a SubjectProviders
func newSubjectProviders(c *WalrusV1Client, namespace string) *subjectProviders {
	return &subjectProviders{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subjectProvider, and returns the corresponding subjectProvider object, and an error if there is any.
func (c *subjectProviders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SubjectProvider, err error) {
	result = &v1.SubjectProvider{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subjectproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SubjectProviders that match those selectors.
func (c *subjectProviders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SubjectProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SubjectProviderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subjectproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subjectProviders.
func (c *subjectProviders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subjectproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subjectProvider and creates it.  Returns the server's representation of the subjectProvider, and an error, if there is any.
func (c *subjectProviders) Create(ctx context.Context, subjectProvider *v1.SubjectProvider, opts metav1.CreateOptions) (result *v1.SubjectProvider, err error) {
	result = &v1.SubjectProvider{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subjectproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subjectProvider).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subjectProvider and updates it. Returns the server's representation of the subjectProvider, and an error, if there is any.
func (c *subjectProviders) Update(ctx context.Context, subjectProvider *v1.SubjectProvider, opts metav1.UpdateOptions) (result *v1.SubjectProvider, err error) {
	result = &v1.SubjectProvider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subjectproviders").
		Name(subjectProvider.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subjectProvider).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subjectProvider and deletes it. Returns an error if one occurs.
func (c *subjectProviders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subjectproviders").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subjectProviders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subjectproviders").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subjectProvider.
func (c *subjectProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SubjectProvider, err error) {
	result = &v1.SubjectProvider{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subjectproviders").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied subjectProvider.
func (c *subjectProviders) Apply(ctx context.Context, subjectProvider *walrusv1.SubjectProviderApplyConfiguration, opts metav1.ApplyOptions) (result *v1.SubjectProvider, err error) {
	if subjectProvider == nil {
		return nil, fmt.Errorf("subjectProvider provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(subjectProvider)
	if err != nil {
		return nil, err
	}
	name := subjectProvider.Name
	if name == nil {
		return nil, fmt.Errorf("subjectProvider.Name must be provided to Apply")
	}
	result = &v1.SubjectProvider{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("subjectproviders").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
