// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/seal-io/walrus/pkg/apis/walrus/v1"
	walrusv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrus/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubjects implements SubjectInterface
type FakeSubjects struct {
	Fake *FakeWalrusV1
	ns   string
}

var subjectsResource = v1.SchemeGroupVersion.WithResource("subjects")

var subjectsKind = v1.SchemeGroupVersion.WithKind("Subject")

// Get takes name of the subject, and returns the corresponding subject object, and an error if there is any.
func (c *FakeSubjects) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Subject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subjectsResource, c.ns, name), &v1.Subject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Subject), err
}

// List takes label and field selectors, and returns the list of Subjects that match those selectors.
func (c *FakeSubjects) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SubjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subjectsResource, subjectsKind, c.ns, opts), &v1.SubjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SubjectList{ListMeta: obj.(*v1.SubjectList).ListMeta}
	for _, item := range obj.(*v1.SubjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subjects.
func (c *FakeSubjects) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subjectsResource, c.ns, opts))

}

// Create takes the representation of a subject and creates it.  Returns the server's representation of the subject, and an error, if there is any.
func (c *FakeSubjects) Create(ctx context.Context, subject *v1.Subject, opts metav1.CreateOptions) (result *v1.Subject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subjectsResource, c.ns, subject), &v1.Subject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Subject), err
}

// Update takes the representation of a subject and updates it. Returns the server's representation of the subject, and an error, if there is any.
func (c *FakeSubjects) Update(ctx context.Context, subject *v1.Subject, opts metav1.UpdateOptions) (result *v1.Subject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subjectsResource, c.ns, subject), &v1.Subject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Subject), err
}

// Delete takes name of the subject and deletes it. Returns an error if one occurs.
func (c *FakeSubjects) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(subjectsResource, c.ns, name, opts), &v1.Subject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubjects) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subjectsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SubjectList{})
	return err
}

// Patch applies the patch and returns the patched subject.
func (c *FakeSubjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Subject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subjectsResource, c.ns, name, pt, data, subresources...), &v1.Subject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Subject), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied subject.
func (c *FakeSubjects) Apply(ctx context.Context, subject *walrusv1.SubjectApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Subject, err error) {
	if subject == nil {
		return nil, fmt.Errorf("subject provided to Apply must not be nil")
	}
	data, err := json.Marshal(subject)
	if err != nil {
		return nil, err
	}
	name := subject.Name
	if name == nil {
		return nil, fmt.Errorf("subject.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subjectsResource, c.ns, *name, types.ApplyPatchType, data), &v1.Subject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Subject), err
}

// Login takes the representation of a subjectLogin and creates it.  Returns the server's representation of the subjectLogin, and an error, if there is any.
func (c *FakeSubjects) Login(ctx context.Context, subjectName string, subjectLogin *v1.SubjectLogin, opts metav1.CreateOptions) (result *v1.SubjectLogin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateSubresourceAction(subjectsResource, subjectName, "login", c.ns, subjectLogin), &v1.SubjectLogin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SubjectLogin), err
}

// CreateToken takes the representation of a subjectToken and creates it.  Returns the server's representation of the subjectToken, and an error, if there is any.
func (c *FakeSubjects) CreateToken(ctx context.Context, subjectName string, subjectToken *v1.SubjectToken, opts metav1.CreateOptions) (result *v1.SubjectToken, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateSubresourceAction(subjectsResource, subjectName, "token", c.ns, subjectToken), &v1.SubjectToken{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SubjectToken), err
}
