// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderBitbucketConfigApplyConfiguration represents an declarative configuration of the SubjectProviderBitbucketConfig type for use
// with apply.
type SubjectProviderBitbucketConfigApplyConfiguration struct {
	ClientID     *string  `json:"clientID,omitempty"`
	ClientSecret *string  `json:"clientSecret,omitempty"`
	Groups       []string `json:"groups,omitempty"`
}

// SubjectProviderBitbucketConfigApplyConfiguration constructs an declarative configuration of the SubjectProviderBitbucketConfig type for use with
// apply.
func SubjectProviderBitbucketConfig() *SubjectProviderBitbucketConfigApplyConfiguration {
	return &SubjectProviderBitbucketConfigApplyConfiguration{}
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *SubjectProviderBitbucketConfigApplyConfiguration) WithClientID(value string) *SubjectProviderBitbucketConfigApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *SubjectProviderBitbucketConfigApplyConfiguration) WithClientSecret(value string) *SubjectProviderBitbucketConfigApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *SubjectProviderBitbucketConfigApplyConfiguration) WithGroups(values ...string) *SubjectProviderBitbucketConfigApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}
