// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderOAuthClaimMappingApplyConfiguration represents an declarative configuration of the SubjectProviderOAuthClaimMapping type for use
// with apply.
type SubjectProviderOAuthClaimMappingApplyConfiguration struct {
	NameKey        *string `json:"nameKey,omitempty"`
	DisplayNameKey *string `json:"displayNameKey,omitempty"`
	EmailKey       *string `json:"emailKey,omitempty"`
	GroupsKey      *string `json:"groupsKey,omitempty"`
}

// SubjectProviderOAuthClaimMappingApplyConfiguration constructs an declarative configuration of the SubjectProviderOAuthClaimMapping type for use with
// apply.
func SubjectProviderOAuthClaimMapping() *SubjectProviderOAuthClaimMappingApplyConfiguration {
	return &SubjectProviderOAuthClaimMappingApplyConfiguration{}
}

// WithNameKey sets the NameKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NameKey field is set to the value of the last call.
func (b *SubjectProviderOAuthClaimMappingApplyConfiguration) WithNameKey(value string) *SubjectProviderOAuthClaimMappingApplyConfiguration {
	b.NameKey = &value
	return b
}

// WithDisplayNameKey sets the DisplayNameKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayNameKey field is set to the value of the last call.
func (b *SubjectProviderOAuthClaimMappingApplyConfiguration) WithDisplayNameKey(value string) *SubjectProviderOAuthClaimMappingApplyConfiguration {
	b.DisplayNameKey = &value
	return b
}

// WithEmailKey sets the EmailKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailKey field is set to the value of the last call.
func (b *SubjectProviderOAuthClaimMappingApplyConfiguration) WithEmailKey(value string) *SubjectProviderOAuthClaimMappingApplyConfiguration {
	b.EmailKey = &value
	return b
}

// WithGroupsKey sets the GroupsKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsKey field is set to the value of the last call.
func (b *SubjectProviderOAuthClaimMappingApplyConfiguration) WithGroupsKey(value string) *SubjectProviderOAuthClaimMappingApplyConfiguration {
	b.GroupsKey = &value
	return b
}
