// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration represents an declarative configuration of the SubjectProviderLdapGroupSearchUserMatcher type for use
// with apply.
type SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration struct {
	GroupAttribute *string `json:"groupAttribute,omitempty"`
	UserAttribute  *string `json:"userAttribute,omitempty"`
}

// SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration constructs an declarative configuration of the SubjectProviderLdapGroupSearchUserMatcher type for use with
// apply.
func SubjectProviderLdapGroupSearchUserMatcher() *SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration {
	return &SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration{}
}

// WithGroupAttribute sets the GroupAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupAttribute field is set to the value of the last call.
func (b *SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration) WithGroupAttribute(value string) *SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration {
	b.GroupAttribute = &value
	return b
}

// WithUserAttribute sets the UserAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserAttribute field is set to the value of the last call.
func (b *SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration) WithUserAttribute(value string) *SubjectProviderLdapGroupSearchUserMatcherApplyConfiguration {
	b.UserAttribute = &value
	return b
}
